name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.15.0]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      # Step 1: Set up Android SDK
      - name: Set up Android SDK
        run: |
          sudo apt update
          sudo apt install -y openjdk-11-jdk
          mkdir -p $HOME/android-sdk
          export ANDROID_HOME=$HOME/android-sdk
          export ANDROID_SDK_ROOT=$HOME/android-sdk
          export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools:$PATH
          echo "export ANDROID_HOME=$HOME/android-sdk" >> ~/.bashrc
          echo "export ANDROID_SDK_ROOT=$HOME/android-sdk" >> ~/.bashrc
          echo "export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools:$PATH" >> ~/.bashrc

      # Step 2: Install Android tools and system images
      - name: Install Android tools
        run: |
          sdkmanager --update
          sdkmanager "platform-tools" "platforms;android-35" "build-tools;35.0.0" "emulator" "system-images;android-35;google_apis;x86_64"
          echo "y" | sdkmanager --licenses

      # Step 3: Create Emulator (AVD)
      - name: Create Android Emulator AVD
        run: |
          echo "no" | avdmanager create avd -n "Pixel_API_35" -d "pixel" -k "system-images;android-35;google_apis;x86_64" --force

      # Step 4: Start Emulator
      - name: Start Android Emulator
        run: |
          nohup emulator -avd Pixel_API_35 -no-window -no-audio -gpu off &
          adb wait-for-device

      # Step 5: Run tests
      - name: Run tests
        run: npm run test:emulator3

      # Step 6: Generate Allure report
      - name: Generate Allure report
        run: npm run allure:generate

      # Step 7: Upload Allure report
      - name: Upload Allure report
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: allure-report
